version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      no_cache: true
    container_name: backend
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      no_cache: true
    container_name: frontend
    ports:
      - "5000:80"